"""annotation_displayName

Revision ID: b7ff618b91a3
Revises: 668bc7219ce9
Create Date: 2025-04-07 00:02:01.672189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ff618b91a3'
down_revision: Union[str, None] = '668bc7219ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('displayName', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotations', 'displayName')
    # ### end Alembic commands ###
