"""VideoSequenceDatatypeFix

Revision ID: 6f02be8a402b
Revises: 4880d1ebbaa4
Create Date: 2025-03-25 01:51:54.104858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f02be8a402b'
down_revision: Union[str, None] = '4880d1ebbaa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'sequence_number')
    op.add_column('videos', sa.Column('sequence_number', sa.Integer, nullable=False))
    op.drop_constraint('videos_uploaded_by_fkey', 'videos', type_='foreignkey')
    op.drop_column('videos', 'uploaded_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('videos_uploaded_by_fkey', 'videos', 'users', ['uploaded_by'], ['id'])
    op.drop_column('videos', 'sequence_number')
    op.add_column('videos', sa.Column('sequence_number', sa.UUID, nullable=False))
    # ### end Alembic commands ###
