"""001_GameAddName

Revision ID: 9bf9bff3033a
Revises: a63109713577
Create Date: 2025-01-29 00:43:07.794129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bf9bff3033a'
down_revision: Union[str, None] = 'a63109713577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'name')
    # ### end Alembic commands ###
