"""002_GameAddTeamName

Revision ID: 4880d1ebbaa4
Revises: 9bf9bff3033a
Create Date: 2025-01-29 15:30:21.583944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4880d1ebbaa4'
down_revision: Union[str, None] = '9bf9bff3033a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('team1_name', sa.String(), nullable=True))
    op.add_column('games', sa.Column('team2_name', sa.String(), nullable=True))
    # ### end Alembic commands ###
    op.execute(
        """
        UPDATE games
        SET team1_name = (SELECT team_name FROM teams WHERE id = games.team1_id),
            team2_name = (SELECT team_name FROM teams WHERE id = games.team2_id)
        """
    )
    op.alter_column('games', 'team1_name', nullable=False)
    op.alter_column('games', 'team2_name', nullable=False)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'team2_name')
    op.drop_column('games', 'team1_name')
    # ### end Alembic commands ###
