"""indexAnnotationColumns

Revision ID: 0665154367e1
Revises: b7ff618b91a3
Create Date: 2025-05-07 18:35:08.468839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0665154367e1'
down_revision: Union[str, None] = 'b7ff618b91a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_annotations_type'), 'annotations', ['type'], unique=False)
    op.create_index(op.f('ix_annotations_video_id'), 'annotations', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotations_video_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_type'), table_name='annotations')
    # ### end Alembic commands ###
