version: '3'
services:
  api:
    image: rust_backend
    environment:
      DATABASE_URL: "postgres://user:pass@db:5432"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3030" # Is going to forward whatever comes on the left port to the right one inside the container
    depends_on:
      - db
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
  api2:
    image: python_backend
    environment:
      DATABASE_URL: "postgresql://user:pass@db:5432"
    build:
      context: ./pythonBackend
      dockerfile: Dockerfile
    ports:
      - "80:3030" # Is going to forward whatever comes on the left port to the right one inside the container
    depends_on:
      - db