services:
  ui:
    image: frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
  api:
    image: python_backend
    build:
      context: .
      dockerfile: ./pythonBackend/Dockerfile
    environment:
     - DATABASE_URL=postgresql://user:pass@db/db
     - APP_DATA_PATH=/var/lib/docker/volumes/api
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - api_data:/var/lib/docker/volumes/api/
  db:
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
      - POSTGRES_PORT=5432
volumes:
  postgres_data:
  api_data:
