"""UUID_primary_keys

Revision ID: 26aec8d857a2
Revises: a384d5008d76
Create Date: 2024-12-11 09:31:16.179102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26aec8d857a2'
down_revision: Union[str, None] = 'a384d5008d76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sports_id', table_name='sports')
    op.drop_table('sports')
    op.alter_column('access_roles', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('access_roles', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('access_roles', 'role_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('access_roles', 'team_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('annotations', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('annotations', 'video_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('games_history', sa.Column('name', sa.String(), nullable=True))
    op.add_column('games_history', sa.Column('sportType', sa.Enum('Football', 'Tennis', name='sporttype'), nullable=True))
    op.alter_column('games_history', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('games_history', 'team1_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('games_history', 'team2_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint('games_history_sport_id_fkey', 'games_history', type_='foreignkey')
    op.drop_constraint('games_history_video_id_fkey', 'games_history', type_='foreignkey')
    op.drop_column('games_history', 'video_order')
    op.drop_column('games_history', 'sport_id')
    op.drop_column('games_history', 'video_id')
    op.alter_column('player_history', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('player_history', 'team_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('player_history', 'player_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('players', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('players_id_seq'::regclass)"))
    op.alter_column('players', 'team_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('roles', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('teams', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('teams_id_seq'::regclass)"))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('videos', sa.Column('name', sa.String(), nullable=True))
    op.alter_column('videos', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('videos', 'uploaded_by',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint('videos_video_path_key', 'videos', type_='unique')
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    op.drop_column('videos', 'video_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('video_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.create_unique_constraint('videos_video_path_key', 'videos', ['video_path'])
    op.alter_column('videos', 'uploaded_by',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('videos', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('videos', 'name')
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('teams', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('teams_id_seq'::regclass)"))
    op.alter_column('roles', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('players', 'team_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('players', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('players_id_seq'::regclass)"))
    op.alter_column('player_history', 'player_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('player_history', 'team_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('player_history', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('games_history', sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('games_history', sa.Column('sport_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('games_history', sa.Column('video_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('games_history_video_id_fkey', 'games_history', 'videos', ['video_id'], ['id'])
    op.create_foreign_key('games_history_sport_id_fkey', 'games_history', 'sports', ['sport_id'], ['id'])
    op.alter_column('games_history', 'team2_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('games_history', 'team1_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('games_history', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('games_history', 'sportType')
    op.drop_column('games_history', 'name')
    op.alter_column('annotations', 'video_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('annotations', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('access_roles', 'team_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('access_roles', 'role_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('access_roles', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('access_roles', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_table('sports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sports_pkey'),
    sa.UniqueConstraint('name', name='sports_name_key')
    )
    op.create_index('ix_sports_id', 'sports', ['id'], unique=False)
    # ### end Alembic commands ###
