name: Test

on: 
  pull_request:

jobs:    
    test:
        name: unit test

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4
            
            - name: Setup Node.js
              id: setup-node
              uses: actions/setup-node@v4
              with:
               node-version-file: .node_version
               cache: npm
               cache-dependency-path: './frontend'
            
            - name: Install dependencies
              id: install
              run: npm install
              working-directory: ./frontend

            - name: Run tests
              id: test
              run: npm test
              working-directory: ./frontend